### ISSUE TITLE
Diminutives

### ISSUE THREAD

**Issue by ftyers** [apertium/apertium-nhi#2]
@Lguyogiro I've analysed the diminutives that you originally had as:
```
!LEXICON Diminutive
!%<Dim1%>@D.PL@:@D.PL@^tzin # ;
!%<Dim2%>@D.PL@:@D.PL@^tzintli # ;
!%<Pl%>%<Dim%>@R.PL@:@R.PL@^tzitzin # ;
```
As,
```
LEXICON Diminutivo

%<dim%>:%>tzin                                     # ; 
@D.Px@%<dim%>%<abs%>:@D.Px@%>tzin%>tli             # ;  ! FIXME: Comprobar análisis
%<dim%>%<pl%>:%>tzi%>tzin                          # ;  ! FIXME: Comprobar análisis
%<dim%>:%>tzi%>tzin                                PossPlural ;  ! FIXME: Comprobar análisis
```

Do you think that this is ok? In the grammar sketch you sent `nhi_Grammar.pdf`, I couldn't find the *-tzintli* diminutive so I analysed it as two suffixes. Does it look reasonable?

**Comment by Lguyogiro** [comment]
LGTM, I think this (two morphemes, `tzin>tli`) is the correct analysis. More about this suffix found [here](https://nahuatl.uoregon.edu/content/tzintli-0)

**Comment by ftyers** [comment]
Great! :) We should check what the syntax is too, e.g. does the *-tzin>tli* form appear in the same places as other absolutives or does it have a different distribution.
